### ISSUE TITLE
correct some mistakes

### ISSUE THREAD

**Issue by yuhaoliu7456** [CaitinZhao/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection#2]
### First：in train.py, line 28 and line 34
model_name = args.model_weights
train_path = args.train_file

### Second: in attention.py line42, line 46, line58
C is float32 here, it should be int32 or int64, so add **int()** over C

### Third: in bilinear_upsampling.py line 18
if you meet error here, please do the modification like below
**conv_utils**.normalize_data_format(data_format) to **K.common**.normalize_data_format(data_format)

**Comment by zwm19950414** [comment]
python train.py
Using TensorFlow backend.
train_file model/vgg16_no_top.h5
model_weights train_pair.txt
0 input_1
1 block1_conv1
2 block1_conv2
3 block1_pool
4 dropout_1
5 block2_conv1
6 block2_conv2
7 block2_pool
8 dropout_2
9 block3_conv1
10 block3_conv2
11 block3_conv3
12 block3_pool
13 dropout_3
14 block4_conv1
15 block4_conv2
16 block4_conv3
17 block4_pool
18 dropout_4
19 block5_conv1
20 block5_conv2
21 block5_conv3
22 dropout_5
23 C4_cfe_cfe0
24 C4_cfe_cfe1_dilation
25 C4_cfe_cfe2_dilation
26 C4_cfe_cfe3_dilation
27 C5_cfe_cfe0
28 C5_cfe_cfe1_dilation
29 C5_cfe_cfe2_dilation
30 C5_cfe_cfe3_dilation
31 C3_cfe_cfe0
32 C3_cfe_cfe1_dilation
33 C3_cfe_cfe2_dilation
34 C3_cfe_cfe3_dilation
35 C4_cfeconcatcfe
36 C5_cfeconcatcfe
37 C3_cfeconcatcfe
38 C4_cfe_BN
39 C5_cfe_BN
40 C3_cfe_BN
41 C4_cfe_relu
42 C5_cfe_relu
43 C3_cfe_relu
44 C4_cfe_up2
45 C5_cfe_up4
46 C345_aspp_concat
47 C345_ChannelWiseAttention_withcpfe_GlobalAveragePooling2D
48 dense_1
49 dense_2
50 C345_ChannelWiseAttention_withcpfe_reshape
51 C345_ChannelWiseAttention_withcpfe_repeat
52 C345_ChannelWiseAttention_withcpfe_multiply
53 C345_conv
54 C345_BN
55 C345_relu
56 C345_up4
57 spatial_attention_1_conv1
58 spatial_attention_2_conv1
59 attention1_1_BN
60 attention2_1_BN
61 C2_conv
62 attention1_1_relu
63 attention2_1_relu
64 C1_conv
65 C2_BN_BN
66 spatial_attention_1_conv2
67 spatial_attention_2_conv2
68 C1_BN_BN
69 C2_BN_relu
70 attention1_2_BN
71 attention2_2_BN
72 C1_BN_relu
73 C2_up2
74 attention1_2_relu
75 attention2_2_relu
76 C12_concat
77 spatial_attention_add
78 C12_conv
79 activation_1
80 C12_BN
81 repeat_1
82 C12_relu
83 C12_atten_mutiply
84 fuse_concat
85 sa
Traceback (most recent call last):
File "train.py", line 72, in
model.load_weights(model_name,by_name=True)
File "/home/lthpc/anaconda3/envs/py27/lib/python2.7/site-packages/keras/engine/topology.py", line 2566, in load_weights
f = h5py.File(filepath, mode='r')
File "/home/lthpc/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in init
fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
File "/home/lthpc/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/h5f.c:2123)
IOError: Unable to open file (File signature not found)
What did you do about it？

**Comment by amlandas78** [comment]
Is it necessary to down sample the train images to 256x256?

**Comment by DHW-Master** [comment]
I have the same problem with you, can you give me a help? Thanks! @zwm19950414

**Comment by IzabelaKrupinska** [comment]
@wukaoliu can You help me? how it should look like in code "int() over C"
def SpatialAttention(inputs,name):
    k = 9
    H, W, C = map(int,inputs.get_shape()[1:])
    attention1 = Conv2D(C / 2, (1, k), padding='same', name=name+'_1_conv1')(inputs)
    attention1 = BN(attention1,'attention1_1')
    attention1 = Conv2D(1, (k, 1), padding='same', name=name + '_1_conv2')(attention1)
    attention1 = BN(attention1, 'attention1_2')
    attention2 = Conv2D(C / 2, (k, 1), padding='same', name=name + '_2_conv1')(inputs)
    attention2 = BN(attention2, 'attention2_1')
    attention2 = Conv2D(1, (1, k), padding='same', name=name + '_2_conv2')(attention2)
    attention2 = BN(attention2, 'attention2_2')
    attention = Add(name=name+'_add')([attention1,attention2])
    attention = Activation('sigmoid')(attention)
    attention = Repeat(repeat_list=[1, 1, 1, C])(attention)
    return attention

def ChannelWiseAttention(inputs,name):
    H, W, C = map(int, inputs.get_shape()[1:])
    attention = GlobalAveragePooling2D(name=name+'_GlobalAveragePooling2D')(inputs)
    attention = Dense(C / 4, activation='relu')(attention)
    attention = Dense(C, activation='sigmoid',activity_regularizer=l1_reg)(attention)
    attention = Reshape((1, 1, C),name=name+'_reshape')(attention)
    attention = Repeat(repeat_list=[1, H, W, 1],name=name+'_repeat')(attention)
    attention = Multiply(name=name + '_multiply')([attention, inputs])
    return attention

**Comment by IzabelaKrupinska** [comment]
I've changed code
def SpatialAttention(inputs,name):
    k = 9
    H, W, C = map(int,inputs.get_shape()[1:])
    attention1 = Conv2D(C / 2, (1, k), padding='same', name=name+'_1_conv1')(inputs)
    attention1 = BN(attention1,'attention1_1')
    attention1 = Conv2D(1, (k, 1), padding='same', name=name + '_1_conv2')(attention1)
    attention1 = BN(attention1, 'attention1_2')
    attention2 = Conv2D(C / 2, (k, 1), padding='same', name=name + '_2_conv1')(inputs)
    attention2 = BN(attention2, 'attention2_1')
    attention2 = Conv2D(1, (1, k), padding='same', name=name + '_2_conv2')(attention2)
    attention2 = BN(attention2, 'attention2_2')
    attention = Add(name=name+'_add')([attention1,attention2])
    attention = Activation('sigmoid')(attention)
    attention = Repeat(repeat_list=[1, 1, 1, C])(attention)
    return attention

def ChannelWiseAttention(inputs,name):
    H, W, C = map(int, inputs.get_shape()[1:])
    attention = GlobalAveragePooling2D(name=name+'_GlobalAveragePooling2D')(inputs)
    attention = Dense**(int(C / 4)**, activation='relu')(attention)
    attention = Dense(C, activation='sigmoid',activity_regularizer=l1_reg)(attention)
    attention = Reshape((1, 1, C),name=name+'_reshape')(attention)
    attention = Repeat(repeat_list=[1, H, W, 1],name=name+'_repeat')(attention)
    attention = Multiply(name=name + '_multiply')([attention, inputs])
    return attention

and I still have  a problem:
InvalidArgumentError: Value for attr 'T' of float is not in the list of allowed values: int32, int64
	; NodeDef: {{node RandomUniform}}; Op<name=RandomUniform; signature=shape:T -> output:dtype; attr=seed:int,default=0; attr=seed2:int,default=0; attr=dtype:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=T:type,allowed=[DT_INT32, DT_INT64]; is_stateful=true> [Op:RandomUniform]


Please, help... @wukaoliu

**Comment by yuhaoliu7456** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I am so sorry that i forget this meaning, but i had reconstructed this code with pytorch. You could contact me by email if you need it.
        Best wishes.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yuhaoliu7456
                            
                    
                        
                            
                                    yuhaoliu7456@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/11/2019 00:15，IzabelaKrupinska<notifications@github.com> wrote： 


@wukaoliu can You help me? how it should look like in code "int() over C"
def SpatialAttention(inputs,name):
k = 9
H, W, C = map(int,inputs.get_shape()[1:])
attention1 = Conv2D(C / 2, (1, k), padding='same', name=name+'_1_conv1')(inputs)
attention1 = BN(attention1,'attention1_1')
attention1 = Conv2D(1, (k, 1), padding='same', name=name + '_1_conv2')(attention1)
attention1 = BN(attention1, 'attention1_2')
attention2 = Conv2D(C / 2, (k, 1), padding='same', name=name + '_2_conv1')(inputs)
attention2 = BN(attention2, 'attention2_1')
attention2 = Conv2D(1, (1, k), padding='same', name=name + '_2_conv2')(attention2)
attention2 = BN(attention2, 'attention2_2')
attention = Add(name=name+'_add')([attention1,attention2])
attention = Activation('sigmoid')(attention)
attention = Repeat(repeat_list=[1, 1, 1, C])(attention)
return attention
def ChannelWiseAttention(inputs,name):
H, W, C = map(int, inputs.get_shape()[1:])
attention = GlobalAveragePooling2D(name=name+'_GlobalAveragePooling2D')(inputs)
attention = Dense(C / 4, activation='relu')(attention)
attention = Dense(C, activation='sigmoid',activity_regularizer=l1_reg)(attention)
attention = Reshape((1, 1, C),name=name+'_reshape')(attention)
attention = Repeat(repeat_list=[1, H, W, 1],name=name+'_repeat')(attention)
attention = Multiply(name=name + '_multiply')([attention, inputs])
return attention

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DoFulangChen** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } I am so sorry that i forget this meaning, but i had reconstructed this code with pytorch. You could contact me by email if you need it. Best wishes. yuhaoliu7456 yuhaoliu7456@gmail.com 签名由 网易邮箱大师 定制 On 11/11/2019 00:15，IzabelaKrupinska<notifications@github.com> wrote： @wukaoliu can You help me? how it should look like in code "int() over C" def SpatialAttention(inputs,name): k = 9 H, W, C = map(int,inputs.get_shape()[1:]) attention1 = Conv2D(C / 2, (1, k), padding='same', name=name+'_1_conv1')(inputs) attention1 = BN(attention1,'attention1_1') attention1 = Conv2D(1, (k, 1), padding='same', name=name + '_1_conv2')(attention1) attention1 = BN(attention1, 'attention1_2') attention2 = Conv2D(C / 2, (k, 1), padding='same', name=name + '_2_conv1')(inputs) attention2 = BN(attention2, 'attention2_1') attention2 = Conv2D(1, (1, k), padding='same', name=name + '_2_conv2')(attention2) attention2 = BN(attention2, 'attention2_2') attention = Add(name=name+'_add')([attention1,attention2]) attention = Activation('sigmoid')(attention) attention = Repeat(repeat_list=[1, 1, 1, C])(attention) return attention def ChannelWiseAttention(inputs,name): H, W, C = map(int, inputs.get_shape()[1:]) attention = GlobalAveragePooling2D(name=name+'_GlobalAveragePooling2D')(inputs) attention = Dense(C / 4, activation='relu')(attention) attention = Dense(C, activation='sigmoid',activity_regularizer=l1_reg)(attention) attention = Reshape((1, 1, C),name=name+'_reshape')(attention) attention = Repeat(repeat_list=[1, H, W, 1],name=name+'_repeat')(attention) attention = Multiply(name=name + '_multiply')([attention, inputs]) return attention —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我正在学习这个内容，不知道可不可以请你解答一下我的这个bug吗？不知是什么原因，感谢！@wukaoliu

Epoch 1/50
lr: 0.010000
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    epochs=epochs,verbose=1,callbacks=callbacks)
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\01\Anaconda3\envs\CV\lib\multiprocessing\pool.py", line 683, in get
    raise self._value
  File "C:\Users\01\Anaconda3\envs\CV\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\01\Anaconda3\envs\CV\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "C:\Users\01\Desktop\sean\PFAN\data.py", line 62, in getTrainGenerator
    x,y = random_crop(x,y)
  File "C:\Users\01\Desktop\sean\PFAN\data.py", line 17, in random_crop
    h,w = y.shape
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by sairajk** [comment]
Hi @wukaoliu  and @amlandas78 ,

You can check my PyTorch implementation of this paper [here](https://github.com/sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/tree/master).
