### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by wbzhang233** [CaitinZhao/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection#24]
help me, pls

```
bafs@bafs-xavier:~/Saliency/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection$ python3 train.py --train_file=train_pair.txt --model_weights=model/vgg16_no_top.h5
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2020-07-16 21:18:06.318968: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
train_file model/vgg16_no_top.h5
model_weights train_pair.txt
<class 'int'>   <class 'int'>
256   256
WARNING:tensorflow:From /usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py:63: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py:492: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py:3630: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py:3458: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py:3013: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/bafs/Saliency/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection/bilinear_upsampling.py:44: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

Traceback (most recent call last):
  File "train.py", line 71, in <module>
    model = VGG16(model_input,dropout=dropout, with_CPFE=with_CPFE, with_CA=with_CA, with_SA=with_SA)
  File "/home/bafs/Saliency/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection/model.py", line 106, in VGG16
    C345 = ChannelWiseAttention(C345, name='C345_ChannelWiseAttention_withcpfe')
  File "/home/bafs/Saliency/cvpr2019_Pyramid-Feature-Attention-Network-for-Saliency-detection/attention.py", line 58, in ChannelWiseAttention
    attention = Dense(C / 4, activation='relu')(attention)
  File "/usr/lib/python3/dist-packages/keras/engine/topology.py", line 576, in __call__
    self.build(input_shapes[0])
  File "/usr/lib/python3/dist-packages/keras/layers/core.py", line 830, in build
    constraint=self.kernel_constraint)
  File "/usr/lib/python3/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keras/engine/topology.py", line 397, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/lib/python3/dist-packages/keras/initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/lib/python3/dist-packages/keras/backend/tensorflow_backend.py", line 3631, in random_uniform
    dtype=dtype, seed=seed)
  File "/home/bafs/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/random_ops.py", line 245, in random_uniform
    rnd = gen_random_ops.random_uniform(shape, dtype, seed=seed1, seed2=seed2)
  File "/home/bafs/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_random_ops.py", line 822, in random_uniform
    name=name)
  File "/home/bafs/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 632, in _apply_op_helper
    param_name=input_name)
  File "/home/bafs/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

```

**Comment by Forrest-Gan** [comment]
you could fix as below:
attention1 = Conv2D(C // 2, (1, k), padding='same', name=name+'_1_conv1')(inputs)

**Comment by xysylvia** [comment]
I have the same error.
where the code I should fix as yours ? pls
```python 
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    model = VGG16(model_input,dropout=dropout, with_CPFE=with_CPFE, with_CA=with_CA, with_SA=with_SA)

  File "D:\A-learning-Ying\fuxian\pytorch-vsumm-reinforce\daima\Pyramid-Feature-Attention-Network-for-Saliency-detection-master\model.py", line 106, in VGG16
    C345 = ChannelWiseAttention(C345, name='C345_ChannelWiseAttention_withcpfe')
  File "D:\A-learning-Ying\fuxian\pytorch-vsumm-reinforce\daima\Pyramid-Feature-Attention-Network-for-Saliency-detection-master\attention.py", line 59, in Channe
lWiseAttention
    attention = Dense(C / 4, activation='relu')(attention)
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\engine\base_layer.py", line 432, in __call__
    self.build(input_shapes[0])
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\layers\core.py", line 872, in build
    constraint=self.kernel_constraint)
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\engine\base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\initializers.py", line 218, in __call__
    dtype=dtype, seed=self.seed)
  File "E:\ADACONDA\Anaconda\lib\site-packages\keras\backend\tensorflow_backend.py", line 4077, in random_uniform
    dtype=dtype, seed=seed)
  File "E:\ADACONDA\Anaconda\lib\site-packages\tensorflow\python\ops\random_ops.py", line 247, in random_uniform
    rnd = gen_random_ops.random_uniform(shape, dtype, seed=seed1, seed2=seed2)
  File "E:\ADACONDA\Anaconda\lib\site-packages\tensorflow\python\ops\gen_random_ops.py", line 820, in random_uniform
    name=name)
  File "E:\ADACONDA\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 626, in _apply_op_helper
    param_name=input_name)
  File "E:\ADACONDA\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64
